### ISSUE TITLE
Latest ADB Launcher.bat leads to empty directory

### ISSUE THREAD

**Issue by thebigsmileXD** [fawazahmed0/Latest-adb-fastboot-installer-for-windows#10]
Running the bat file opens an empty directory.
It would be a lot more useful to download and put ADB & Fastboot into that folder automatically.

The tool gives no output about where it puts ADB & Fastboot. I had to dig though the source code just to find it.

**Comment by fawazahmed0** [comment]
In that empty directory, you can paste the files you would like to flash into your phone, like `twrp.img` or `system.img`

and run your commands in the command prompt like:
`fastboot flash recovery twrp.img`



Thanks
