### ISSUE TITLE
how to add custom usb vid pid?

### ISSUE THREAD

**Issue by qianfan-Zhao** [fawazahmed0/Latest-adb-fastboot-installer-for-windows#12]
Hi:

thanks for this tools that I installed adb and fastboot. but I had a custom board, is there has a way to adding usb vid/pid to driver?

Thanks

**Comment by fawazahmed0** [comment]
This tool should automatically add the usd vid/pid

**Comment by qianfan-Zhao** [comment]
My custom board isn't android. It's powered by u-boot. and seems the usb descriptors can't recognised by this tools.
So is there has an easy way to adding usb vid/pid to window's usbdriver?

**Comment by fawazahmed0** [comment]
can you provide the usb vid/pid of your device

**Comment by qianfan-Zhao** [comment]
the default configuration for allwinner devices: 0x1f3a/0x1010
the default configuration for am335x devices: 0x0451/0xd022

**Comment by fawazahmed0** [comment]
can you provide the complete name, for example it might be `XXX\VID_0451&PID_D022`
For android devices it's usually starts with USB, for example `USB\VID_0451&PID_D022` , but in your case, it might start with something else.
so can you please provide the complete name

**Comment by qianfan-Zhao** [comment]
the hardware id shown in device manager is "USB\VID_1F3A&PID_1010", it's quite complte to android devices.

**Comment by fawazahmed0** [comment]
then I am not sure why my tool is not working for you, because my tool will install drivers for unknown devices starting with `USB\`.
I don't think I can help you

**Comment by qianfan-Zhao** [comment]
Thanks for yours guide and my board can work now. 

I had installed libusb driver by zadig few days ago and want bind fastboot usb deivce to wsl but failed. This tools search all unkown devices starting with "USB\", so I uninstall libusb driver and run this tools again, it works.

Thanks.

**Comment by qianfan-Zhao** [comment]
Just a suggestion:

It's better if this tools can print which usb device is detected when installing.

**Comment by fawazahmed0** [comment]
Thank you for confirming
