### ISSUE TITLE
This website isn't a platform for forcing religious ideologies on others

### ISSUE THREAD

**Issue by Aporue76** [fawazahmed0/Latest-adb-fastboot-installer-for-windows#8]
Please STOP pushing your religion on others. Forcing your religious beliefs like that is EXTREMELY disrespectful. The world is much bigger and more diverse than you think. There are many other different cultures and beliefs around the world, and yours isn't appealing to anyone  - outside your religious bubble. If you want to believe that everyone who doesn't share your beliefs deserves to be tortured with fire forever, as your preferred religious book claims, that's your prerogative, but keep it to yourself and ONLY to yourself. That is - if you want to share this world with others PEACEFULLY.

**Comment by thebigsmileXD** [comment]
I do agree that religion has nothing to do inside a computer program / tool.

**Comment by XxnittanixX** [comment]
i actually quite appreciate the little quotes here and there so if you would  STFU  and deal with it

**Comment by Aporue76** [comment]
> i actually quite appreciate the little quotes here and there so if you would STFU and deal with it

I'm sure you'd like me to "shut the f*** up". How islamic of you.
